algoritmo "ContadorParesComLacoDeRepeticao"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson, vulgo(Obama)
// Descrição: Essa lógica irá contar os pares
// Autor(a): Gabriel de souza almeida
// Data atual: 30/03/2025

Var
   numero: inteiro

Inicio
   Escreval("Contador de Pares")
   Escreval("")
   numero <- 2
   repita
      Escreval(numero)
      numero <- numero + 2
   ate (numero > 20)

Fimalgoritmo